### ISSUE TITLE
Make a option to keep dimming on

### ISSUE THREAD

**Issue by JumpIn-Git** [marcelohdez/dim#11]
This is the only program out there to dim the screen below minimum for wayland, i would like a mode to keep the dimming on until the command is stopped, like dim -r for repeat or -c for continues

**Comment by marcelohdez** [comment]
Hey! Just added the `-p`, `--passthrough` option to allow input to be ignored and passed to the surfaces under dim, should be in a release soon, combining this with the infinite duration (`-d 0`) you can have permanent dimming.

As for stopping the process, I do think worrying about IPC is out-of-scope for dim however you can make your own scripts where you summon dim at a certain time, with a keybind, etc., and then just stop it with `pkill dim`.

Hope this helps :D

**Comment by JumpIn-Git** [comment]
YES IT WORKS, thanks so much. me and my eyes are in debt to you
